name    'branan-minecraft'
version '1.0.0'
source  'https://github.com/branan/puppet-module-minecraft'
author  'Branan Purvine-Riley'
license 'Apache License 2.0'
summary 'Minecraft Server'
description 'Install and manage a Minecraft server'
project_page 'https://github.com/branan/puppet-module-minecraft'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'puppetlabs/java',   '>= 0.1.6'
dependency 'branan/s3file',     '>= 1.0.0'
